# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a11ae8d5cc700699e476155bc40581c1ec1634d6dc66d7baf180dc5d5e9667415622c097caa4bfe7f7c7da2757c1d3ae4e45eb73dcb6424d18e864141fa92ed

test:
  secret_key_base: 13b7e19041037c47db479a955e4d60b9ad39bf8d9ab43a3bcb0c7caeff7cd477b0df7b1780e87e430e86769df30d4a500250e73e9051d640178836a5b95b6d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
